{{- if $.Values.providerIntegration.apps }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cluster.resource.name" $ }}-migrate-apps
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "cluster.labels.common.all" $ | nindent 4 }}
  annotations:
    helm.sh/hook: pre-upgrade
    helm.sh/hook-weight: "-20"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
{{- end }}
