appName: coredns-extensions
chartName: coredns-extensions
configKey: coreDnsExtensions
clusterValues:
  configMap: true
  secret: false
dependsOn: vertical-pod-autoscaler-crd
namespace: kube-system
# used by renovate
# repo: giantswarm/coredns-extensions-app
version: 0.1.2
