appName: teleport-kube-agent
configKey: teleportKubeAgent
namespace: kube-system
# used by renovate
# repo: giantswarm/teleport-kube-agent-app
version: 0.10.6
extraConfigs:
- kind: ConfigMap
  name: "{{ $.Values.global.metadata.name }}-teleport-kube-agent-config"
  namespace: "{{ $.Release.Namespace }}"
