appName: cert-exporter
configKey: certExporter
clusterValues:
  configMap: true
  secret: false
dependsOn: kyverno-crds
namespace: kube-system
# used by renovate
# repo: giantswarm/cert-exporter
version: 2.9.15
