appName: cluster-autoscaler-app-bundle
chartName: cluster-autoscaler-app-bundle
configKey: clusterAutoscaler
clusterValues:
  configMap: true
  secret: true
inCluster: true
dependsOn: kyverno-crds
namespace: kube-system
# used by renovate
# repo: giantswarm/cluster-autoscaler-app
version: 1.34.1-1-84d6643ef01c7cddaaf73bc8d198707c15600ba6
