{{- if $.Values.providerIntegration.monitoring.apiServerProbe.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "cluster.labels.common.all" $ | nindent 4 }}
  name: {{ include "cluster.resource.name" $ }}-apiserver-probe
  namespace: kube-system
spec:
  endpoints:
  - interval: {{ $.Values.providerIntegration.monitoring.apiServerProbe.interval }}
    metricRelabelings:
    - action: replace
      sourceLabels:
      - instance
      targetLabel: instance
    - action: replace
      replacement: {{ include "cluster.resource.name" $ }}-apiserver
      sourceLabels:
      - target
      targetLabel: target
    params:
      module:
      - {{ $.Values.providerIntegration.monitoring.apiServerProbe.module }}
      target:
      - https://api.{{ include "cluster.resource.name" $ }}.{{ $.Values.global.connectivity.baseDomain }}:{{ $.Values.global.controlPlane.apiServerPort }}/readyz
    path: /probe
    port: http
    scheme: http
    scrapeTimeout: {{ $.Values.providerIntegration.monitoring.apiServerProbe.scrapeTimeout }}
  jobLabel: prometheus-blackbox-exporter
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      app.kubernetes.io/instance: prometheus-blackbox-exporter
      app.kubernetes.io/name: prometheus-blackbox-exporter
{{- end }}
